### ISSUE TITLE
push-client should support trusted_certs

### ISSUE THREAD

**Issue by tduffield** [chef-boneyard/opscode-pushy-client#54]
When running the push-jobs-client against a chef server with an unsigned SSL certificate, I got the following error: 

```
2015-01-28_22:05:35.84355 INFO: [builder1-ubuntu-1204] Using node name: builder1-ubuntu-1204
2015-01-28_22:05:35.84357 INFO: [builder1-ubuntu-1204] Using Chef server: https://192.168.33.33/organizations/cd
2015-01-28_22:05:35.84358 INFO: [builder1-ubuntu-1204] Using private key: /etc/chef/client.pem
2015-01-28_22:05:35.84358 INFO: [builder1-ubuntu-1204] Using org name: cd
2015-01-28_22:05:35.84359 INFO: [builder1-ubuntu-1204] Incarnation ID: 89191f4e-c1ad-467d-afac-4368e59fc63b
2015-01-28_22:05:35.84359 INFO: [builder1-ubuntu-1204] Starting client ...
2015-01-28_22:05:35.84361 INFO: [builder1-ubuntu-1204] Retrieving configuration from https://192.168.33.33/organizations/cd/pushy/config/builder1-ubuntu-1204 ...
2015-01-28_22:05:35.85244 /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
2015-01-28_22:05:35.85246       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
2015-01-28_22:05:35.85246       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
2015-01-28_22:05:35.85247       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
2015-01-28_22:05:35.85247       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:800:in `connect'
2015-01-28_22:05:35.85248       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
2015-01-28_22:05:35.85250       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:745:in `start'
2015-01-28_22:05:35.85250       from /opt/opscode-push-jobs-client/embedded/lib/ruby/1.9.1/net/http.rb:1285:in `request'
2015-01-28_22:05:35.85251       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest/rest_request.rb:99:in `block in call'
2015-01-28_22:05:35.85251       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest/rest_request.rb:114:in `hide_net_http_bug'
2015-01-28_22:05:35.85253       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest/rest_request.rb:98:in `call'
2015-01-28_22:05:35.85253       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest.rb:166:in `block in raw_http_request'
2015-01-28_22:05:35.85254       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest.rb:280:in `retriable_rest_request'
2015-01-28_22:05:35.85254       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest.rb:164:in `raw_http_request'
2015-01-28_22:05:35.85255       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest.rb:158:in `api_request'
2015-01-28_22:05:35.85255       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/rest.rb:99:in `get'
2015-01-28_22:05:35.85256       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-0.0.1/lib/pushy_client.rb:172:in `get_config'
2015-01-28_22:05:35.85256       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-0.0.1/lib/pushy_client.rb:72:in `start'
2015-01-28_22:05:35.85258       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-0.0.1/lib/pushy_client/cli.rb:106:in `run_application'
2015-01-28_22:05:35.85258       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/chef-11.2.0/lib/chef/application.rb:73:in `run'
2015-01-28_22:05:35.85259       from /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-0.0.1/bin/pushy-client:8:in `<top (required)>'
2015-01-28_22:05:35.85259       from /opt/opscode-push-jobs-client/bin/pushy-client:23:in `load'
2015-01-28_22:05:35.85260       from /opt/opscode-push-jobs-client/bin/pushy-client:23:in `<main>'
```

The /etc/chef/client.rb in question was configured as such:

``` ruby
chef_server_url "https://192.168.33.33/organizations/cd"
validation_client_name "deliver_us_from_jenkins"
validation_key "/etc/chef/validator.pem"
ssl_verify_mode :verify_peer
node_name "builder1-ubuntu-1204"
encrypted_data_bag_secret '/etc/chef/encrypted_data_bag_secret'
```

The chef-client version on the push-client node was 11.16 while the chef-server version was 12.0.1. 

It looks as is the push-jobs client is not accepting the ssl certs in the trusted_certs directory.

**Comment by manderson26** [comment]
This is likely to hit other people going forward, need to fix soon.

**Comment by docwhat** [comment]
Oddly, I'm hitting this on Windows, but not RHEL.  On Windows `chef-client` connects just fine, but the `pushy` service doesn't.
